"""refactored f1 user table to anime app version

Revision ID: 9d76c03afd2b
Revises: e2d938aaf932
Create Date: 2026-09-10 23:17:28.433763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d76c03afd2b'
down_revision: Union[str, Sequence[str], None] = 'e2d938aaf932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_code'), table_name='users')
    op.drop_column('users', 'rank_elo')
    op.drop_column('users', 'f1_team')
    op.drop_column('users', 'email_verification_expiry')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', postgresql.ENUM('ROOKIE', 'AMATEUR', 'PRO', 'WORLD_CLASS', 'CHAMPION', name='userrank'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_verification_expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('f1_team', postgresql.ENUM('MERCEDES', 'FERRARI', 'RED_BULL', 'MCLAREN', 'ALPINE', 'ASTON_MARTIN', 'RACING_BULLS', 'HAAS', 'WILLIAMS', 'AUDI', 'CADILLAC', name='f1teams'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rank_elo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_email_verification_code'), 'users', ['email_verification_code'], unique=True)
    # ### end Alembic commands ###
