"""add cascade delete to refresh_token user_id fk

Revision ID: e2d938aaf932
Revises: e5fc16ed8fca
Create Date: 2026-09-04 00:12:43.732836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d938aaf932'
down_revision: Union[str, Sequence[str], None] = 'e5fc16ed8fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_token_user_id_fkey'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key('refresh_token_user_id_fkey', 'refresh_token', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_token_user_id_fkey', 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_user_id_fkey'), 'refresh_token', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
