"""updated user model for email_verification

Revision ID: e5fc16ed8fca
Revises: 504b08293020
Create Date: 2026-08-15 22:58:41.717668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fc16ed8fca'
down_revision: Union[str, Sequence[str], None] = '504b08293020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expiry', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_email_verification_code'), 'users', ['email_verification_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_verification_code'), table_name='users')
    op.drop_column('users', 'email_verification_expiry')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'email_verification_code')
    # ### end Alembic commands ###
